### ISSUE TITLE
Module crashes under Companion v3.0 and 3.1

### ISSUE THREAD

**Issue by SK-RaoSel** [bitfocus/companion-module-netio-powerbox#2]
Hi Folks, 

the Module is crashing under v3.0.0 2023-07-15. I had ti downgrade companion to v3.0.0 2023-06-21. any Idea?

**Comment by SK-RaoSel** [comment]
Modul crashes also under Version [3.0.1 (3.0.1+6068-stable-a05a9c89)]

**Comment by SK-RaoSel** [comment]
Hi Folks, any idea? i need this module works... 

Trace: Init failed: ReferenceError: instanceStatus is not defined
    at C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:241191
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:210623

error: Failed to init: Error: instanceStatus is not defined ReferenceError: instanceStatus is not defined
    at t.InstanceBase.init (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:346)
    at C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:241127
    at C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:210462
    at t.default._tryToStartAnother (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:209509)
    at C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:210669
    at new Promise (<anonymous>)
    at t.default.add (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:210312)
    at t.InstanceBase._handleInit (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:240571)
    at t.IpcWrapper.receivedMessage (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:225557)
    at process.<anonymous> (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:240055)

**Comment by SK-RaoSel** [comment]
hej @josephdadams

On Version [3.1.0 (3.1.0+6148-beta-abace5ac)](https://bitfocus.io/companion/) the Plugin still crashes.

23.09.08 15:24:32 Instance/ModuleHost: Starting connection: "PowerBOX-1"(DsOVs2QLXT0mT6r4n1584)
23.09.08 15:24:32 Instance/ModuleHost: Connection "PowerBOX-1" started
23.09.08 15:24:32 Instance/ModuleHost: Registered module client "DsOVs2QLXT0mT6r4n1584"
23.09.08 15:24:32 Instance/ModuleHost: Instance "PowerBOX-1" failed to init: Error: instanceStatus is not defined ReferenceError: instanceStatus is not defined
    at t.InstanceBase.init (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:346)
    at C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:241127
    at C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:210462
    at t.default._tryToStartAnother (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:209509)
    at C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:210669
    at new Promise (<anonymous>)
    at t.default.add (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:210312)
    at t.InstanceBase._handleInit (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:240571)
    at t.IpcWrapper.receivedMessage (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:225557)
    at process.<anonymous> (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:240055)
23.09.08 15:24:32 Instance/ModuleHost: Connection "PowerBOX-1" stopped

**Comment by josephdadams** [comment]
It is a simple bug due to `instanceStatus` instead of `InstanceStatus` and can be fixed

**Comment by josephdadams** [comment]
I have fixed this for you and pushed to betas: https://github.com/bitfocus/companion-bundled-modules/actions/runs/6122384015

**Comment by SK-RaoSel** [comment]
Hej @josephdadams, thank you for your help. Unfurtonatly the plugin still doesent work. Now i get the failure message: "Warning Ready".

any idea?

**Comment by josephdadams** [comment]
please try v2.0.2 of the module. thank you and have a nice day

**Comment by SK-RaoSel** [comment]
Dear @josephdadams, 

thank you very much for yout work. The Plugin unfurtunatly not work. I can connect with the Poweradapter but the commands on companion do not have an effect. i running at the moment Beta: 6212. the Firmware of Netio is 4.0.0.

**Comment by SK-RaoSel** [comment]
On the issue tracker i got e huge error and this data: 

ReferenceError: body is not defined
    at t.InstanceBase.setOutput (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:2364)
    at Object.callback (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:873)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.ActionManager.handleExecuteAction (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:227852)

Node.js v18.17.1

and 

error: Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:225067)
    at C:\Program Files\Companion\resources\bundled-modules\netio-powerbox\main.js:2:218148

**Comment by josephdadams** [comment]
I pushed another fix, please try v2.0.3 of the module

**Comment by SK-RaoSel** [comment]
@josephdadams 

Works! Thank you!

**Comment by josephdadams** [comment]
Glad I could help
